daysUntilStale: 1

daysUntilClose: 1

# Label to use when marking as stale
staleLabel: redirect-to-dev-community

# Comment to post when marking as stale. Set to `false` to disable
markComment: >
  In order to consolidate to fewer feedback channels, we've moved suggestions and
  issue reporting to [Developer Community](https://developercommunity.visualstudio.com/spaces/21/index.html).

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false

# Limit to only `issues` or `pulls`
only: issues
