resources:
- repo: self
queue:
  demands: msbuild

variables:
  BuildConfiguration: 'Debug'
  TeamName: 'Package Experience'

steps:
- template: build/build.yml
  parameters:
    push: false
    nuspecProperties: 'VersionSuffix=-PR-$(Build.BuildNumber)'
