resources:
- repo: self
queue:
  demands: msbuild

variables:
  BuildConfiguration: 'Debug'
steps:
- template: build/build.yml
  parameters:
    push: true
    nuspecProperties: 'VersionSuffix=-CI-$(Build.BuildNumber)'
