resources:
- repo: self

queue:
  demands: msbuild

trigger: none

variables:
  BuildConfiguration: 'Debug'
  TeamName: 'Package Experience'

steps:
- template: build/build.yml
  parameters:
    nuspecProperties: 'VersionSuffix=-PR-$(Build.BuildNumber)'
