resources:
- repo: self

queue:
  demands: msbuild

variables:
  BuildConfiguration: 'Release'
  TeamName: 'Package Experience'

steps:
- powershell: 'mkdir $(Build.SourcesDirectory)\keys; cp -Verbose $(KeyLocation) $(Build.SourcesDirectory)\keys\; dir $(Build.SourcesDirectory)\keys\'
  displayName: Copy public key

- template: build/build.yml
  parameters:
    push: false
    sign: true
